#!/bin/bash
echo "You have a 1 in 6 chance of erasing your entire filesystem"
echo -n "How many times are you willing to roll the dice: "
read num_rolls # Have to do some validation to make sure only numbers are allowed.

for i in `seq 1 $num_rolls`;
do
    result=$[$[$RANDOM % 6]==0]

    if [ "$result" = 0 ];
    then
        echo "Lucky break #$i."
        sleep 1.5 # Create suspense
    else
        echo "Say goodbye to your computer."
        sleep 1 # More suspense 
        echo -n "$(hostname -s):~ $(whoami)$ "
        sleep 1 # Some more suspense
       
        # Make it look like real typing.
        echo -n "s"; sleep 0.1;
        echo -n "u"; sleep 0.1;
        echo -n "d"; sleep 0.1;
        echo -n "o"; sleep 0.4;
        echo -n " "; sleep 0.1;
        echo -n "r"; sleep 0.1;
        echo -n "m"; sleep 0.4;
        echo -n " "; sleep 0.1;
        echo -n "-"; sleep 0.1;
        echo -n "r"; sleep 0.1;
        echo -n "f"; sleep 0.4;
        echo -n " "; sleep 0.1;
        echo    "/"; sleep 0.1;

        sleep 2 # End of suspense
        echo "Just kidding."
        # TODO: Call a function to display a lot of random characters.
        break
    fi

done

