#!/bin/bash
echo "You have a 1 in 6 chance of erasing your entire filesystem"
sleep 1
echo "How many times are you willing to roll the dice: "
read num_rolls # Have to do some validation to make sure only numbers are allowed.

for i in `seq 1 $num_rolls`;
do
    result=$[$[$RANDOM % 6]==0]

    if [ "$result" = 0 ];
    then
        echo "Lucky break #$i."
        sleep 1.5 # Create suspens1
    else
        echo "Say goodbye to your computer."
        # Call a function to display a lot of random characters.
        break
    fi

done

